### ISSUE TITLE
FFT.pas Not Found !

### ISSUE THREAD

**Issue by walwalwalides** [hello-sea/SHM_StructuralHealthMonitoring#1]
Hi Sea ,I dont found FFT.pas in code souce...,Thx

**Comment by hello-sea** [comment]
@walwalwalides  Hello, thank you for your feedback. The FFT.pas source code is not available due to copyright issues. The open source version of the [FFT code](https://github.com/LUXOPHIA/FFTW) is provided here and needs to be modified to work.
See code:
[1] (Pascal ) https://github.com/LUXOPHIA/FFTW
[2] https://github.com/FFTW/fftw3
[3] http://www.fftw.org/

**Comment by hello-sea** [comment]
If you still have problems during use, you can open this "issue" at any time and I will try my best to help and improve the project.

**Comment by hello-sea** [comment]
If you still have problems during use, you can open this "issue" at any time and I will try my best to help and improve this project.

**Comment by walwalwalides** [comment]
Thank you so much for your help i really appreciate it 👍
